#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Prettier formatting
yarn prettier . --write

# ESLint
yarn nx affected:lint --fix

# Terraform formatting
if command -v terraform > /dev/null
then
  terraform fmt ./terraform
else
  >&2 echo "$(tput setaf 1)Terraform could not be found in the system binaries!"
  >&2 echo "$(tput setaf 1)Please make sure it's setup properly an the 'terraform' command is available in the path.$(tput sgr0)"
fi

# Add changes to the current commit
# This only re-adds files that were already staged
git diff --name-only --cached | xargs git add
