import '../global.css';
import '@sugaming/sugaming-ui/global.css';

import React from 'react';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { ThemeProvider } from '@sugaming/sugaming-ui/lib/providers/theme-provider';
import { AxiomWebVitals } from 'next-axiom';
import { SpeedInsights } from '@vercel/speed-insights/dist/next/index';
import { Analytics } from '@vercel/analytics/dist/next/index';
import { locales } from '../i18n';

export const metadata = {
  title: 'Welcome to sugaming-admin',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  if (!locales.includes(locale)) {
    notFound();
  }

  const messages = useMessages();
  return (
    <html lang={locale}>
      <body>
        {/* Enable production logging and insights */}
        <AxiomWebVitals />
        <SpeedInsights />
        <Analytics />

        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
